name: Build SPA
description: Setup some stuff
inputs:
  ecr-repo-name:
    required: true
  build-id:
    required: true
  s3-output-path:
    required: true
  aws-region:
    required: true
  github-token:
    required: true
runs:
  using: composite
  steps:
    - run: echo Hello ${{ inputs.ecr-repo-name }}
      shell: bash
    - run: echo Goodbye
      shell: bash
